Kimjimin
Team-QSS/Platformgame-QSS pull request #5
Opened 2020-10-11 05:09 UTC by kimjimin4471

2020-10-11 05:52 UTC, Hulkstd commented
여기 PR에 무엇이 적용되었는지 적어. 그래야 리뷰를 보지

2020-10-11 06:13 UTC, sonohoshi commented
`GameManager.cs` 의 prevX, intervalY 변수가 코드 컨벤션을 지키지 않고 작성 됨.
같은 클래스의 MissileReferenceTime, Missile, MissileTime, MissileRespawn 변수가 코드 컨벤션을 지키지 않고 작성 됨.

`MissileCtrl.cs` 의 `void OnTriggerEnter2D(Collider2D col)` 메소드의 if문이 코드 컨벤션을 지키지 않고 작성 됨.

2020-10-11 06:14 UTC, sonohoshi commented
+ 김지민은 커밋할 때 메세지에 점 찍을 정도로 변경사항이 없으면 굳이 커밋하지 마라. 리뷰 할 커밋만 늘어난다.

2020-10-11 06:16 UTC, sonohoshi approved these changes, later dismissed

2020-10-14 07:40 UTC, Hulkstd commented on Platformgame/Assets/0. KimJiMin/GameManager.cs
> +    private float intervalY;//Y 간격
```suggestion
    private float _prevX; //이전 x값을 저장하는 변수
    private float _intervalY;//Y 간격
```
위 변수가 코드 컨벤션을 지키지 않고 작성 됨.

2020-10-14 07:42 UTC, Hulkstd commented on Platformgame/Assets/0. KimJiMin/GameManager.cs
> +    private float MissileTime;//미사일 생성 쿨타임
```suggestion
    public float missileReferenceTime; //미사일 생성 주기
    public GameObject missile; //미사일 프리팹
    
    private Vector3 _missileRespawn;//미사일을 생성하는 곳의 좌표
    private float _missileTime;//미사일 생성 쿨타임
```

2020-10-14 07:44 UTC, Hulkstd commented on Platformgame/Assets/0. KimJiMin/MissileCtrl.cs
> +            Destroy(col.gameObject);
```suggestion
        if (col.gameObject.tag.Equals("Player"))
        {
            Destroy(col.gameObject);
        }
```
위 변수가 코드 컨벤션을 지키지 않고 작성 됨.

2020-11-04 08:25 UTC, sonohoshi requested changes

2020-11-04 08:25 UTC, sonohoshi commented on New_PlatformGame/Assets/1. Script/MissileSpawn.cs
> +    private Transform transform;
```suggestion
    private Vector3 CameraPositionTopRight;
    private Transform transform;
```
`private변수 앞에는 _로 시작한다.` 라는 코드 컨벤션을 지키지 않았어요.
`변수 이름은 소문자로, 메서드와 클래스 이름은 대문자로 시작한다.` 라는 컨벤션도 지켜지지 않았습니다.

2020-11-04 08:25 UTC, sonohoshi commented on New_PlatformGame/Assets/1. Script/GameManager.cs
>      }
```suggestion
    void MissileSummoning() //미사일 생성
    {
        CameraPositionTopRight = Camera.main.ScreenToWorldPoint(new Vector3(Screen.width,Screen.height, 0));
        MissileRespawn = new Vector3(Random.Range(CameraPositionBottomLeft.x, CameraPositionTopRight.x), CameraPositionTopRight.y,0);
        Instantiate(Missile, MissileRespawn, Quaternion.identity);
        CameraPositionTopRight = Camera.main.ScreenToWorldPoint(new Vector3(Screen.width, Screen.height, 0));
        Instantiate(Missile, new Vector3(MissileRespawn.x, CameraPositionTopRight.y, 0), Quaternion.identity);
    }
```
사용되지 않는 메소드는 제거 바랍니다.

2020-11-04 08:25 UTC, sonohoshi commented on New_PlatformGame/Assets/NewPlayerMovement.cs
> +        _jumpBarSprite = _jumpBar.GetComponent<SpriteRenderer>();
```suggestion
        _jumpBarSprite = _jumpBar.GetComponent<SpriteRenderer>();
```
`GetComponent로 가져올 변수는 _(component type)로 통일` 하라는 코드 컨벤션이 있는데, 이 경우 어떤 오브젝트의 컴포넌트인지 상세히 알 수 없게 됩니다. 코드 컨벤션에 맞게 바꾸면 `_spriteRenderer` 라는 이름으로 고쳐야 하는데, 해당 코드 컨벤션을 수정하는 것을 추천합니다.

2020-11-04 08:25 UTC, sonohoshi commented on New_PlatformGame/Assets/NewPlayerMovement.cs
> +    private Vector2 _getvel; //Move 함수에서 캐릭터의 속도를 받는 변수
```suggestion
    private Vector2 _getvel; //Move 함수에서 캐릭터의 속도를 받는 변수
```
`카멜 표기법 잘 지키기` 규칙이 지켜지지 않았습니다. `getvel` -> `getVel` 로 고쳐야하고, Vel을 Velocity로 풀어 쓰는 것을 추천합니다.

2020-11-04 08:25 UTC, sonohoshi commented on New_PlatformGame/Assets/1. Script/GameManager.cs
```suggestion
    private Vector3 CameraPositionTopRight; //카메라 위쪽의 Y좌표값을 가져오는 역할
    private Vector3 CameraPositionBottomLeft;
```
`변수 이름은 소문자로, 메서드와 클래스 이름은 대문자로 시작한다.` 라는 코드 컨벤션을 지키지 않았습니다.

2020-11-04 08:25 UTC, sonohoshi commented on Platformgame/Assets/0. KimJiMin/MissileCtrl.cs
```suggestion
    private float _bombSpeed = 1.5f; //미사일 속도
    public float _bombSpeed; //미사일 속도
    public float MissileReferenceTime; //미사일 생성 주기
    public GameObject Missile; //미사일 프리팹
    private readonly Vector3 _direction = Vector3.down;
```
`private, public 변수 선언은 나누어 정리` 규칙 및 `변수 이름은 소문자로, 메서드와 클래스 이름은 대문자로 시작한다.` 규칙이 지켜지지 않았습니다.

2020-11-04 08:25 UTC, sonohoshi commented on Platformgame/Assets/3. Scripts/CameraCtrl.cs
> +    }
```suggestion
    private void GameOver()
    {
        //게임 끝내기
    }
```
`함수는 동사로 하기 CantMove -> MakeCanNotMove()` 규칙이 어겨졌습니다.
`MakeGameOver` 혹은 `EndGame` 등으로 고치는 것을 권장합니다.

2020-11-04 08:26 UTC, sonohoshi submitted a review, later dismissed

2020-11-20 08:17 UTC, sonohoshi commented on New_PlatformGame/Assets/1. Script/GameManager.cs
>      private float intervalY;//Y 간격
```suggestion
    private Vector3 CameraPositionTopRight; //카메라 위쪽의 Y좌표값을 가져오는 역할
    private Vector3 CameraPositionBottomLeft;
    private float prevX; //이전 x값을 저장하는 변수
    private float intervalY;//Y 간격
```

코드 컨벤션 좀

2020-11-20 08:17 UTC, sonohoshi approved these changes

2020-11-20 08:18 UTC, merged